org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
# Ini jangan dihapus, karena ini path ke jbr android studio adel
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr
kotlin.incremental=false
kotlin.incremental.android=false
kotlin.incremental.useClasspathSnapshot=false