name: upsend_karyawan
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  # Perbaikan 1: flutter_svg ditaruh sejajar di sini
  flutter_svg: ^2.3.0

  cupertino_icons: ^1.0.8
  dio: ^5.10.0
  shared_preferences: ^2.5.5
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  camera: ^0.11.0
  google_mlkit_face_detection: ^0.12.0
  image_picker: ^1.2.0
  dotted_border: ^3.1.0
  flutter_lints: ^6.0.0
  bloc: ^9.2.1
  google_fonts: ^8.2.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  file_picker: ^8.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700

  # Perbaikan 2: Spasi assets dirapikan (maju 2 spasi dari kiri)
  assets:
    - assets/images/
    - assets/fonts/
    
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#2F3B69"
  adaptive_icon_foreground: "assets/images/app_icon.png"